"""create_sales_and_dispatch_tables

Revision ID: 25f5d5e2b0b9
Revises: 76c7dc85e4e3
Create Date: 2026-09-09 11:37:41.785430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f5d5e2b0b9'
down_revision: Union[str, Sequence[str], None] = '76c7dc85e4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_name'), 'buyers', ['name'], unique=False)
    op.create_table('dispatch_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispatch_number', sa.String(length=50), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('waste_grade_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('tare_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bales_count', sa.Integer(), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WEIGHED_OUT', 'DISPATCHED', 'CANCELLED', name='dispatch_status_enum'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', name='payment_status_enum'), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['waste_grade_id'], ['waste_grades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_orders_dispatch_number'), 'dispatch_orders', ['dispatch_number'], unique=True)
    op.create_index(op.f('ix_dispatch_orders_plant_id'), 'dispatch_orders', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_orders_plant_id'), table_name='dispatch_orders')
    op.drop_index(op.f('ix_dispatch_orders_dispatch_number'), table_name='dispatch_orders')
    op.drop_table('dispatch_orders')
    op.drop_index(op.f('ix_buyers_name'), table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
