"""add_stock_ledger_and_indexes

Revision ID: 5b2ff6694c9e
Revises: d93ba1ff4a3e
Create Date: 2026-09-13 16:59:40.752067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2ff6694c9e'
down_revision: Union[str, Sequence[str], None] = 'd93ba1ff4a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('PRODUCTION_INFLOW', 'DISPATCH_OUTFLOW', 'STOCK_ADJUSTMENT', 'AUDIT_RECONCILIATION', name='stock_movement_type_enum'), nullable=False),
    sa.Column('delta_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delta_bales', sa.Integer(), nullable=False),
    sa.Column('balance_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_bales', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_id'], ['finished_goods_inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ledgers_inventory_id'), 'stock_ledgers', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_movement_type'), 'stock_ledgers', ['movement_type'], unique=False)
    op.create_index('idx_plant_grade_stock', 'finished_goods_inventory', ['plant_id', 'waste_grade_id', 'current_stock_kg'], unique=False)
    op.drop_constraint(op.f('finished_goods_inventory_plant_id_fkey'), 'finished_goods_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'finished_goods_inventory', 'plants', ['plant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finished_goods_inventory', type_='foreignkey')
    op.create_foreign_key(op.f('finished_goods_inventory_plant_id_fkey'), 'finished_goods_inventory', 'plants', ['plant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('idx_plant_grade_stock', table_name='finished_goods_inventory')
    op.drop_index(op.f('ix_stock_ledgers_movement_type'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_inventory_id'), table_name='stock_ledgers')
    op.drop_table('stock_ledgers')
    # ### end Alembic commands ###
