"""create_operations_and_dpr_tables

Revision ID: 76c7dc85e4e3
Revises: e8ccdc7c23c6
Create Date: 2026-09-09 10:00:02.928260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c7dc85e4e3'
down_revision: Union[str, Sequence[str], None] = 'e8ccdc7c23c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_progress_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=False),
    sa.Column('electricity_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diesel_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('strapping_wire_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_raw_processed_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_output_produced_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_inert_waste_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mass_balance_variance_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_progress_reports_plant_id'), 'daily_progress_reports', ['plant_id'], unique=False)
    op.create_index(op.f('ix_daily_progress_reports_report_date'), 'daily_progress_reports', ['report_date'], unique=False)
    op.create_table('downtime_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('MACHINE_BREAKDOWN', 'POWER_OUTAGE', 'FEEDSTOCK_SHORTAGE', 'MAINTENANCE', 'LABOR_UNAVAILABLE', 'OTHER', name='downtime_reason_enum'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['daily_progress_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downtime_logs_dpr_id'), 'downtime_logs', ['dpr_id'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('waste_grade_id', sa.UUID(), nullable=False),
    sa.Column('output_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bales_produced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dpr_id'], ['daily_progress_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_grade_id'], ['waste_grades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_logs_dpr_id'), 'production_logs', ['dpr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_logs_dpr_id'), table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index(op.f('ix_downtime_logs_dpr_id'), table_name='downtime_logs')
    op.drop_table('downtime_logs')
    op.drop_index(op.f('ix_daily_progress_reports_report_date'), table_name='daily_progress_reports')
    op.drop_index(op.f('ix_daily_progress_reports_plant_id'), table_name='daily_progress_reports')
    op.drop_table('daily_progress_reports')
    # ### end Alembic commands ###
