"""create_procurement_and_inventory

Revision ID: adee823deee6
Revises: 
Create Date: 2026-09-09 09:24:59.677483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adee823deee6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_code'), 'plants', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'PLANT_MANAGER', 'WEIGHBRIDGE_OPERATOR', 'HR_OFFICER', 'SALES_LOGISTICS', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_plant_id'), 'users', ['plant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vendor_type', sa.Enum('KABADIWALA', 'INDUSTRIAL_GENERATOR', 'MUNICIPAL', 'OTHER', name='vendor_type_enum'), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('bank_account_no', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_plant_id'), 'vendors', ['plant_id'], unique=False)
    op.create_table('waste_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('grade_code', sa.String(length=50), nullable=False),
    sa.Column('current_rate_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deduction_method', sa.Enum('FLAT_PERCENTAGE', 'SLAB', 'MANUAL_ASSESSMENT', name='deduction_method_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_grades_plant_id'), 'waste_grades', ['plant_id'], unique=False)
    op.create_table('grn_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('grn_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('waste_grade_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('gross_weight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tare_weight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_weight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moisture_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contamination_deduction_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accepted_net_weight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_payable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('load_photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['waste_grade_id'], ['waste_grades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grn_records_grn_number'), 'grn_records', ['grn_number'], unique=True)
    op.create_index(op.f('ix_grn_records_plant_id'), 'grn_records', ['plant_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('grn_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('RAW', 'SORTED', 'PROCESSED_BALED', 'FINISHED_GOODS', name='batch_stage_enum'), nullable=False),
    sa.Column('yard_location', sa.String(length=50), nullable=True),
    sa.Column('current_quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grn_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_code'), 'batches', ['batch_code'], unique=True)
    op.create_index(op.f('ix_batches_plant_id'), 'batches', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batches_plant_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_code'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_grn_records_plant_id'), table_name='grn_records')
    op.drop_index(op.f('ix_grn_records_grn_number'), table_name='grn_records')
    op.drop_table('grn_records')
    op.drop_index(op.f('ix_waste_grades_plant_id'), table_name='waste_grades')
    op.drop_table('waste_grades')
    op.drop_index(op.f('ix_vendors_plant_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_plant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plants_code'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
