"""create_finished_goods_inventory_table

Revision ID: b529d644e3a3
Revises: 25f5d5e2b0b9
Create Date: 2026-09-09 11:51:33.439859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b529d644e3a3'
down_revision: Union[str, Sequence[str], None] = '25f5d5e2b0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_goods_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('waste_grade_id', sa.UUID(), nullable=False),
    sa.Column('current_stock_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bales_in_stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['waste_grade_id'], ['waste_grades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'waste_grade_id', name='uq_plant_waste_grade_inventory')
    )
    op.create_index(op.f('ix_finished_goods_inventory_plant_id'), 'finished_goods_inventory', ['plant_id'], unique=False)
    op.create_index(op.f('ix_finished_goods_inventory_waste_grade_id'), 'finished_goods_inventory', ['waste_grade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finished_goods_inventory_waste_grade_id'), table_name='finished_goods_inventory')
    op.drop_index(op.f('ix_finished_goods_inventory_plant_id'), table_name='finished_goods_inventory')
    op.drop_table('finished_goods_inventory')
    # ### end Alembic commands ###
