"""update_hr_payroll_tables

Revision ID: f1e5cec1ffab
Revises: 05fcf7f21540
Create Date: 2026-09-13 13:52:33.521963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e5cec1ffab'
down_revision: Union[str, Sequence[str], None] = '05fcf7f21540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attendance_plant_date', 'attendance_records', ['plant_id', 'attendance_date'], unique=False)
    op.create_unique_constraint('uq_employee_attendance_date', 'attendance_records', ['employee_id', 'attendance_date'])
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index('ix_employees_plant_active', 'employees', ['plant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_employees_role'), 'employees', ['role'], unique=False)
    op.create_index('ix_payslips_plant_period', 'payslips', ['plant_id', 'year', 'month'], unique=False)
    op.create_unique_constraint('uq_employee_monthly_payslip', 'payslips', ['employee_id', 'month', 'year'])
    op.create_index('ix_advances_employee_status', 'salary_advances', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_salary_advances_status'), 'salary_advances', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_advances_status'), table_name='salary_advances')
    op.drop_index('ix_advances_employee_status', table_name='salary_advances')
    op.drop_constraint('uq_employee_monthly_payslip', 'payslips', type_='unique')
    op.drop_index('ix_payslips_plant_period', table_name='payslips')
    op.drop_index(op.f('ix_employees_role'), table_name='employees')
    op.drop_index('ix_employees_plant_active', table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_constraint('uq_employee_attendance_date', 'attendance_records', type_='unique')
    op.drop_index('ix_attendance_plant_date', table_name='attendance_records')
    # ### end Alembic commands ###
