"""create_products_materials_and_composition

Revision ID: f998becb5216
Revises: 5b2ff6694c9e
Create Date: 2026-10-02 12:00:06.654393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f998becb5216'
down_revision: Union[str, Sequence[str], None] = '5b2ff6694c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_categories_name'), 'material_categories', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_measure', sa.String(length=30), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('material_sub_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['material_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_sub_categories_category_id'), 'material_sub_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_material_sub_categories_code'), 'material_sub_categories', ['code'], unique=True)
    op.create_table('product_material_compositions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sub_category_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'GRAMS', 'MT', name='weight_unit_enum'), nullable=False),
    sa.Column('percentage_share', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_category_id'], ['material_sub_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'sub_category_id', name='uq_product_material_subcategory')
    )
    op.create_index(op.f('ix_product_material_compositions_product_id'), 'product_material_compositions', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_material_compositions_sub_category_id'), 'product_material_compositions', ['sub_category_id'], unique=False)
    op.create_index(op.f('ix_batches_grn_id'), 'batches', ['grn_id'], unique=False)
    op.create_index(op.f('ix_grn_records_vendor_id'), 'grn_records', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_grn_records_waste_grade_id'), 'grn_records', ['waste_grade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grn_records_waste_grade_id'), table_name='grn_records')
    op.drop_index(op.f('ix_grn_records_vendor_id'), table_name='grn_records')
    op.drop_index(op.f('ix_batches_grn_id'), table_name='batches')
    op.drop_index(op.f('ix_product_material_compositions_sub_category_id'), table_name='product_material_compositions')
    op.drop_index(op.f('ix_product_material_compositions_product_id'), table_name='product_material_compositions')
    op.drop_table('product_material_compositions')
    op.drop_index(op.f('ix_material_sub_categories_code'), table_name='material_sub_categories')
    op.drop_index(op.f('ix_material_sub_categories_category_id'), table_name='material_sub_categories')
    op.drop_table('material_sub_categories')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_material_categories_name'), table_name='material_categories')
    op.drop_table('material_categories')
    # ### end Alembic commands ###
